name: Terraform

on:
  push:
    branches:
      - main  # Change this to your branch name
  pull_request:
    branches:
      - main  # Change this to your branch name

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify your Terraform version

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_example: ${{ secrets.TF_VAR_EXAMPLE }}  # Add any required environment variables
